name: xtables
channels:
- conda-forge
- defaults
dependencies:
- fire=0.1.3
- html5lib=1.0.1
- beautifulsoup4=4.7.1
- lxml=4.3.4
- pandas=0.24.2
- beautifulsoup4=4.7.1
- numpy=1.15.4
- python=3.7.1
- pyahocorasick=1.4.0
- Unidecode=1.0.23
